<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYTzRf5w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYTzRf5w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYTzRf5w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYTzRf5w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYTzRf5w\App_KernelDevDebugContainer([
    'container.build_hash' => 'YTzRf5w',
    'container.build_id' => '4e74e9a0',
    'container.build_time' => 1691952859,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYTzRf5w');
